theme = "solarized_light"

[editor]
line-number = "relative"
mouse = true
color-modes = true
true-color = true
bufferline = "always"
gutters = ["line-numbers", "diagnostics", "spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.statusline]
left = ["mode", "file-name", "version-control"]
right = ["workspace-diagnostics", "position", "position-percentage"]
